apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mariadb-root-password: YWRtaW4=     # "admin" en base64
  mariadb-password: YWRtaW4=         # "admin" en base64
