apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-app
  namespace: trivy-system
spec:
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts/
    chart: trivy-app
    targetRevision: latest
    helm:
      values: |
        trivy:
          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
