apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivy-dashboard-ingress
  namespace: trivy-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: trivy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trivy-dashboard
                port:
                  number: 8080
