apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: mariadb
  annotations:
    kubernetes.io/ingress.class: nginx       # ou traefik selon ton cluster
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: phpmyadmin.local         # change par ton domaine
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
