apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: mariadb
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP  # interne au cluster
