apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  mariadb-root-password: bXlwYXNzd29yZA==  # "mypassword" en base64
  galera-sst-password: c3N0cGFzcw==         # "sstpass" en base64
