apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  # mot de passe root encod√© en base64 (echo -n "mypassword" | base64)
  mariadb-root-password: bXlwYXNzd29yZA==
