apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  mariadb-root-password: cm9vdHBhc3N3b3Jk   # rootpassword en base64
  mariadb-user: d3BfdXNlcg==               # wp_user
  mariadb-password: d3BfcGFzc3dvcmQ=        # wp_password
  mariadb-database: d3BfZGF0YWJhc2U=        # wp_database
